### ISSUE TITLE
Cannot access private repo owned by different user or organization

### ISSUE THREAD

**Issue by cinderblock** [winfsp/hubfs#1]
I have a private repo on my account and orgs, shared with other users.

When I use HUBFS, (on Windows, installed with `.msi`, authenticated with "Preform GitHub Auth") I can access my private repos without any issue. All features that I've tested work as expected.

However, if I try to access a private repo owned by a different user or org, even if I'm the owner of the org, I cannot access them.

They also do not show up in the top level user's (or org's) folder(s).

If I try to go to the project's URL directly, I get a "Windows cannot access" error with code: `0x80004005` that looks identical to what you see when you access a nonexistent repo:
![image](https://user-images.githubusercontent.com/419955/152076553-07e74c45-98dd-4161-ac8e-7fd6683c1a77.png)

**Comment by cinderblock** [comment]
I have double checked that HUBFS has been granted access to my org.

**Comment by cinderblock** [comment]
I found the debug option in the source. Not seeing a clear error though:

```log
PS C:\Users\camer> & 'C:\Program Files\HUBFS\hubfs.exe' -o debug github.com/TWILL-Tech/Controller T:
2022/02/03 18:36:42 providers.(*githubClient).getOwner("TWILL-Tech") = <nil>
2022/02/03 18:36:42 providers.(*githubClient).getRepositories("TWILL-Tech") = <nil>
2022/02/03 18:36:42 main.(*Hubfs).Getattr("/", 0xffffffffffffffff) = (-2, &fuse.Stat_t{Dev:0x0, Ino:0x0, Mode:0x0, Nlink:0x0, Uid:0x0, Gid:0x0, Rdev:0x0, Size:0, Atim:fuse.Timespec{Sec:0, Nsec:0}, Mtim:fuse.Timespec{Sec:0, Nsec:0}, Ctim:fuse.Timespec{Sec:0, Nsec:0}, Blksize:0, Blocks:0, Birthtim:fuse.Timespec{Sec:0, Nsec:0}, Flags:0x0})
The service hubfs has failed to start (Status=c0000034).
```

**Comment by billziss-gh** [comment]
I am taking a small break after the latest release of WinFsp, but I am hoping to focus on hubfs again soon.

**Comment by cinderblock** [comment]
No worries. I'm excited to use this FUSE more. Would really help one of my co-worker's workflows.

I'll poke around some if I find the time. If you have ideas of things for me to look at, I'm all ears!

**Comment by billziss-gh** [comment]
I believe commit 2ed298cd38418534d02925c8e4a780868f7ce852 should address this issue.

This commit will be included in the next Beta which should be available soon.

**Comment by billziss-gh** [comment]
Closing this as [HUBFS 2022 Beta1](https://github.com/winfsp/hubfs/releases/tag/v1.0B1) is out. Please reopen if you find that the problem persists.
