### ISSUE TITLE
Drive is empty

### ISSUE THREAD

**Issue by SuperJMN** [winfsp/hubfs#12]
Hi!

I've followed all the steps to setup HubFS

- Authenticated using the browser
![image](https://github.com/winfsp/hubfs/assets/3109851/79be8750-15e9-402c-a1b5-fe0646c0aaee)

- Mounted the drive 
![image](https://github.com/winfsp/hubfs/assets/3109851/b423882c-e558-450d-90e2-5ab64e6cd91c)

But I see nothing inside. 

Using Windows 11 and the latest version of WinFsp.

**Comment by billziss-gh** [comment]
The top level directory does not list any directories, because it would have to list millions(?) of GitHub users. Try looking for a particular user's repositories like `M:\SuperJMN`.

**Comment by SuperJMN** [comment]
You're so right! It wasn't clear to me until you told me. It works so well.
Thanks a lot and congratulations on the project. It rocks!
