### ISSUE TITLE
Changes to mounted repository are not kept

### ISSUE THREAD

**Issue by d-w-moore2** [winfsp/hubfs#4]
On:
   - Ubuntu 18.04
   
I've followed the instructions in the README and managed to mount a Github private repository , authorizing my Ubuntu PC via the one-time code.

I mount and then create / write top level files in the repo : 
```
$ hubfs ~/mnt/
<... use one-time code and launch browser to authorize device aka PC ... >
$ # in another terminal ... :
$ cd ~/mnt/d-w-moore2/practice/master ; touch a ; vim README.md # make changes and save
$ cd ~ ; fusermount -u mnt
```
Then:
  - I do not notice Github in the browser showing any commits on `master `to reflect the touched `a`  file and `README.md` changes.
  - re-mounting and cd'ing into the directory again, I can confirm the changes have not been saved

**Comment by billziss-gh** [comment]
This is by design.

HUBFS use case scenario is to support browsing of repositories and allow local builds to be performed without cloning. HUBFS is not intended as a replacement for git. All changes to the repository are local and are not pushed into the origin repository.

**Comment by d-w-moore** [comment]
I see.  It's more secure that way too, I suppose.  As far as workflows for tracking any edits, changes could still be copied to a locally cloned repository - on detection of `.keep` files, and with use of a tool like `rsync` possibly.  Thanks for the clarification!

**Comment by d-w-moore2** [comment]
I see. It's more secure that way too, I suppose. As far as workflows for tracking any edits, changes could still be copied to a locally cloned repository - on detection of .keep files, and with use of a tool like rsync possibly. Thanks for the clarification!
