### ISSUE TITLE
Device flow is disabled

### ISSUE THREAD

**Issue by Minion3665** [winfsp/hubfs#6]
When I try to run hubfs I get the following error
```
{23:39}~ ➭ hubfs /mnt
hubfs: client error: Device Flow must be explicitly enabled for this App (device_flow_disabled)
```

I suspect this is due to the recent github change which means that [GitHub now requires device flow to be enabled for apps rather than having it enabled by default](https://github.blog/changelog/2022-03-16-enable-oauth-device-authentication-flow-for-apps/) and the hubfs app does not yet have this enabled.

Update: a workaround in the meantime could be to use the `-auth` option to specify a different way of authenticating with GitHub. `hubfs -auth optional /mnt`, for example, doesn't give this error

**Comment by billziss-gh** [comment]
@Minion3665 thank you very much for identifying both the problem and the solution. I have now enabled "Device Flow" for hubfs.

I am closing this, but please reopen if you still have problems.
