### ISSUE TITLE
[QUE] Can hubfs currently be used with a Gitlab Free on premise server?

### ISSUE THREAD

**Issue by claudio-salvio** [winfsp/hubfs#7]
Hello @billziss-gh,

Beyond not having explicit Gitlab support yet, is there any possibility to use **hubs** with a **Gitlab Free server hosted on premise**?

🙏Thanks for developing this useful software and making it accessible to the community.

Regards,
Claudio Salvio

**Comment by billziss-gh** [comment]
HUBFS currently only knows how to interface with GitHub. I expect that some changes would be required in order for this to work with GitLab or GitLab on premise.

I intend to adding GitLab support some time in the future.

**Comment by claudio-salvio** [comment]
Hello @billziss-gh 

Thank you for your prompt reply.

It would be great if it interacts with other servers like Gitlab or Bitbucket.
I for one would really appreciate it if you support Gitlab.
As a follower of your projects I will keep an eye out for any new developments in this regard.

Thanks again for your excellent work, not only on this project but on all the others (winfsp, winspd, sshfs-win, etc.).
Honestly, I don't know another person who is doing such an interesting work on file systems and sharing it with the community.

Best regards,
Claudio Salvio

**Comment by billziss-gh** [comment]
Thank you for the kind words, @claudio-salvio.

**Comment by billziss-gh** [comment]
Closing this as GitLab support has now been added.

**Comment by claudio-salvio** [comment]
> Closing this as GitLab support has now been added.

Hello @billziss-gh 

I had not seen your comment ! 
What a great news!

Thank you very much for adding support for Gitlab.
As soon as I have a few minutes I will start using it.

Best regards,
Claudio
